import 'package:flutter/material.dart';

import './models/category.dart';
//import './models/meal.dart';
import 'meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Anna Special ',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

// ignore: unnecessary_const
const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    duration: 10,
    ingredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
          'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Kachori',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Kachori_the_favourite_north_Indian_breakfast.JPG/2560px-Kachori_the_favourite_north_Indian_breakfast.JPG',
    duration: 40,
    ingredients: [
      '2 Cups refined flour',
      '1/4 cup ghee',
      'to taste salt',
      'cold water (to mix)',
      'for deep-frying oil',
      'For the filling:',
      '3/4 cup black gram (husked), soaked ',
      '2 tbsp oil1 tsp cumin seeds',
      '1/8 tsp asafoetida (hing)',
      '3/4 tsp garam masala',
      '3/4 tsp chilli powder',
      '2 tbsp fennel seeds, powdered',
      '2 tsp coriander powder',
      'to taste salt',
      '1 1/2 tsp mango powder',
    ],
    steps: [
      'Mix in the flour and salt.',
      'Add the ghee to the flour.',
      'Make it into a crumbly mixture with the tips of your fingers',
      'Add enough water, to make it into a stiffish dough (it should not yield easily when a finger is pressed into it). Cover and leave to rest for at least 15-20 minutes',
      'Make marble-sized balls of the lentil mixture (called pithee) wetting your hands as and when necessary to prevent the mixture from sticking to them. Cover with a cloth till ready to fill.',
      'Make about 20 smooth balls from the dough. Roll them out till 1/4 " thick (about 5 cms/ 2 in diameter).',
      'Take one piece of rolled dough and pinch the edge all around, leaving the center thicker',
      'Dampen the pressed edges, place a ball of filling in the center and bring wet edges together, covering the filling completely. Press together to seal.',
      'Place this piece in your palm and with the heal of the other palm, press gently in the center. Flatten a bit with palm first then roll it lightly in a round',
      'The kachauris are now ready to be fried. Heat the oil in a kadahi.',
      'When a piece of dough dropped in oil comes up at once, put in as many kachauris that can fit in; turn over immediately and lower heat to medium.',
      'Fry them till they all turn an even golden in color; reducing the heat from medium to low.',
      'Takes about 10 minutes for one side and 7-8 minutes on the other. Remove from oil, drain and place on absorbent paper. Serve hot.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: ['c8'],
    title: 'Dal Bati ',
    affordability: Affordability.Pricey,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.secondrecipe.com/wp-content/uploads/2020/12/dal-bati-churma.jpg',
    duration: 30,
    ingredients: [
      '2 cup wheat flour / atta',
      '¼ tsp salt',
      '▢¼ tsp baking powder',
      '¼ cup ghee / clarified butter',
      'water to knead',
      'for dal',
      '½ cup moong dal / green gram dal',
      '¼ cup masoor dal / pink lentils',
      '¼ cup chana dal / bengal gram dal (soaked 30 minutes)',
      '3 cup water',
      '3 tsp ghee / clarified butter',
      '1 tsp mustard',
      '1 tsp cumin / jeera',
      'pinch hing / asafoetida',
      '1 onion (finely chopped)',
      '1 tsp ginger garlic paste',
      '1 green chilli (slit)',
      '1 to mato (finely chopped)',
      '¼ tsp turmeric',
      '½ tsp kashmiri red chilli powder',
      '¼ tsp garam masala',
      '1 tsp salt',
      '1 cup water',
      '2 tbsp coriander (finely chopped',
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm12',
    categories: ['c10'],
    title: 'Pista Kulfi ',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'http://www.indobase.com/recipes/rec-images/pista-kulfi.jpg',
    duration: 30,
    ingredients: [
      '2 Cups of evaporated milk',
      '1 Cup condensed milk',
      '16 oz Whipped cream',
      '1/2 tsp Ground green cardamom powder',
      '1/4 Cup of green sliced pista',
      'Sugar to taste'
    ],
    steps: [
      'Pour evaporated milk, condensed milk and whipped cream in a mixer.',
      'Add ground green cardamom powder & sugar.',
      'Blend well the mixture.',
      'Then add sliced green pista and stir slightly.',
      'Now fill the mixture in Kulfi cones or ice cream tray.',
      'Place it in the freezer for a whole night (minimum 6 hours).',
      'At the time of serving, keep the outer surface of the ice cream tray or cones in contact with hot water for just 1-3 seconds and remove it in a plate.',
      'Pista Kulfi is ready to serve.'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm13',
    categories: ['c6'],
    title: 'Rasam',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.herzindagi.info/image/2020/Apr/south-indian-food-recipes-two.jpg',
    duration: 30,
    ingredients: [
      '2 chopped tomatoes',
      '1 pinch asafoetida',
      '1/4 tsp cumin seeds',
      '1/2 tsp peppercorns',
      '1/4 piece ginger',
      '2-3 curry leaves',
      '2 tbsp chopped coriander leaves',
      'Salt as required',
      '1 cup of water',
      '1/4 tsp ghee',
      '1/4 tsp mustard seeds',
    ],
    steps: [
      'Soak the tomatoes and ginger in lukewarm water with a pinch of salt. ',
      'In a blender, add tomatoes, asafoetida, cumin seeds, peppercorns, ginger, curry leaves, coriander leaves and salt.',
      'Heat water in a pan on a medium flame. Add the ground paste and bring it to a boil. Cook for a few minutes and then switch off the flame and keep it aside.',
      'Heat ghee in a pan and add mustard seeds to it. Once they start to crackle, add them to the rasam. You can also add some curry leaves and green chillies to make it tastier. '
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm14',
    categories: ['c6'],
    title: 'Dosa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://sukhis.com/app/uploads/2020/01/Dosa.jpg',
    duration: 30,
    ingredients: [
      '2 chopped tomatoes',
      '1 pinch asafoetida',
      '1/4 tsp cumin seeds',
      '1/2 tsp peppercorns',
      '1/4 piece ginger',
      '2-3 curry leaves',
      '2 tbsp chopped coriander leaves',
      'Salt as required',
      '1 cup of water',
      '1/4 tsp ghee',
      '1/4 tsp mustard seeds',
    ],
    steps: [
      'Soak the tomatoes and ginger in lukewarm water with a pinch of salt. ',
      'In a blender, add tomatoes, asafoetida, cumin seeds, peppercorns, ginger, curry leaves, coriander leaves and salt.',
      'Heat water in a pan on a medium flame. Add the ground paste and bring it to a boil. Cook for a few minutes and then switch off the flame and keep it aside.',
      'Heat ghee in a pan and add mustard seeds to it. Once they start to crackle, add them to the rasam. You can also add some curry leaves and green chillies to make it tastier. '
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'c7',
      'c2',
    ],
    title: 'Khaman',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://pulses.org/images/com_yoorecipe/cropped-khaman.jpg',
    duration: 25,
    ingredients: [
      '1 cup rice',
      '1 cup urad dal',
      '1 cup yellow moong daal',
      '3 cups sour buttermilk',
      '2 green chillies, crushed fine',
      '1/4 tsp ginger grated fine',
      '1/2 tsp oil',
      '3 pinches red chilli powder',
      '1/2 tbsp coriander finely chopped',
      'salt to taste',
    ],
    steps: [
      'Mix the rice and dal, wash, drain and dry on a clean cloth for a few hours.',
      'The grain should be completely dry. Grind to a coarse flour in dry grinder or at the flour mill.',
      'This flour should be like very fine sooji in texture. Store in airtight container and use as required.',
      'Will keep good up to 2 months.',
      'To make khaman, take 1 cup flour in a bowl. Add buttermilk, and mix well.',
      'Keep aside for 4-5 hours. Dissolve soda bicarbonate in the oil. Add to batter.',
      'Mix all ingredients except red chilli powder and coriander.',
      'Pour immediately in a 6" diameter greased plate. Steam over water either in a cooker or steamer.',
      'Pierce with a knife to check; it should come out clean if done.',
      'Sprinkle the chilli powder and coriander, steam again for 2-3 minutes.',
      'Cut into squares or diamonds and serve hot with coconut chutney.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm16',
    categories: [
      'c5',
    ],
    title: 'Fruit Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i0.wp.com/vegecravings.com/wp-content/uploads/2016/03/Fruit-Chaat-Recipe-Instructions-Step-By-Step.jpg?w=1612&quality=65&strip=all&ssl=1',
    duration: 20,
    ingredients: [
      'all types of fruits you want',
    ],
    steps: [
      'wash all the fruits ',
      'Cut and peel all the fruits',
      'Decorate nicely as you want',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
];
